### ISSUE TITLE
Official TypeScript Typings

### ISSUE THREAD

**Issue by KitsuneDev** [sourcechord/electron-typescript-sample#1]
Now electron has it's official TS Typings!! [More details here.](https://electron.atom.io/blog/2017/06/01/typescript)

**Comment by sourcechord** [comment]
Hi, @GabrielTK.

Thanks for the information.
I've updated packages, but electron v1.7.3 is still pre-release version.

Please try `feature/electron1.7` branch.
https://github.com/sourcechord/electron-typescript-sample/tree/feature/electron1.7

**Comment by sourcechord** [comment]
`feature/electron1.7`branch is merged to master.
